#Port
server:
  port: ${SERVER_PORT:8080}

#Application name
spring:
  application:
    name: identity-service

#DB Configuration
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
