#Port
server:
  port: ${SERVER_PORT:8080}

#Application name
spring:
  application:
    name: identity-service

#DB Configuration
  datasource:
    url: jdbc:postgresql://localhost:5433/db_banking
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

#Kafka Config
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka-topic: banking-topic
