#Application name
spring:
  application:
    name: identity-service

#DB Configuration
  datasource:
    url: jdbc:postgresql://localhost:5433/db_banking
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
